[#3] 로그인/로그아웃 기능 구현 PR
f-lab-edu/Hello-World pull request #8
Opened 2021-01-27 17:12 UTC by msugo1

## [#3] 로그인 및 로그아웃 기능 구현
- 유저의 서비스 이용을 위한 로그인 및 로그아웃 기능 구현(세션 방식)
- 로그인 성공/실패(예외)에 대한 테스트 케이스 작성
- 서비스계층 테스트 역할을 좀더 명확하게 분리(회원가입 요청 처리  테스트, 회원가입 시 유효성 검사 테스트, 유저 로그인 및 로그아웃 테스트)
- `Mockito`를 이용해 `UserController`를 다른 계층으로부터 고립시켜 단위테스트생성

2021-01-28 03:57 UTC, f-lab-dev approved these changes

2021-01-28 03:57 UTC, f-lab-dev commented on src/main/java/me/soo/helloworld/HelloworldApplication.java
> +@EnableCaching
이 어노테이션은 어떤 것 때문에 달아주셨나요?

2021-01-28 03:57 UTC, f-lab-dev commented on src/main/java/me/soo/helloworld/service/UserServiceImpl.java
> +        if (httpSession.getAttribute("userId") != null) {
`httpSession.getAttribute("userId")` 이런 로그인(인증)과 관련된 책임은 별도로 빼는게 낫지 않을까요?

2021-01-28 03:57 UTC, f-lab-dev commented on src/main/java/me/soo/helloworld/service/UserServiceImpl.java
> +    public void logoutRequest(HttpSession httpSession) {
`Request`는 굳이 달지 않아도 로그아웃이라는 행위를 충분히 표현할 수 있을 것 같네요~

2021-01-28 07:44 UTC, msugo1 commented on src/main/java/me/soo/helloworld/HelloworldApplication.java
> +@EnableCaching
`Reddis` 설정보고 따라하면서 붙여놨었던 것 같아요. 일단 이 단계에서는 Reddis가 필요하지 않아서 의존성이랑 `ReddisConfig` 파일은 제거 했는데 그 때 저 어노테이션은 잘 안보이는 위치에 있어서 깜빡한 것 같습니다. 지적해 주셔서 감사합니다.

2021-01-28 07:48 UTC, msugo1 commented on src/main/java/me/soo/helloworld/service/UserServiceImpl.java
> +    public void logoutRequest(HttpSession httpSession) {
네 `logout`으로 수정하겠습니다.

2021-01-28 07:54 UTC, msugo1 commented on src/main/java/me/soo/helloworld/service/UserServiceImpl.java
> +        if (httpSession.getAttribute("userId") != null) {
넵 안그래도 작성해놓고 리팩토링이 필요해보여서 저 부분만 따로 분리해서 UserService에 다른 메소드로 만들어 놓는게 좋을지 아니면 로그인 인증관련 클래스 자체를 하나 더 만드는게 좋을지 계속 고민하고 있었습니다.  이 둘 중 선택에 근거가 되는 것이 차후에 다른 클래스/메소드에서도 같은 내용이 사용될지 인가요??

2021-01-29 08:02 UTC, f-lab-dev commented on src/main/java/me/soo/helloworld/service/UserServiceImpl.java
> +        if (httpSession.getAttribute("userId") != null) {
단순 그것뿐만은 아니라 `단일 책임 원칙`도 생각해보시면 좋을 것 같아요.

**유저의 정보를 관리하는 것과 서비스의 인증/인가는 같은 책임인가** 에 대해서요

2021-01-30 12:53 UTC, f-lab-dev commented on src/main/java/me/soo/helloworld/service/LoginService.java
> +    public void logout(HttpSession httpSession);
만약 세션 방식이 아닌 로그인을 구현하려고 할때 이 `HttpSession` 인자가 문제가 되지 않을까요?

2021-01-31 02:05 UTC, msugo1 commented on src/main/java/me/soo/helloworld/service/LoginService.java
> +    public void logout(HttpSession httpSession);
로그인 인터페이스를 구현해놓은 이유가 나중에 로그인 방식을 바꿀 때 유연하게 대처하려고 한 부분인데 Session인자 자체가 이를 막는다는 것을 간과했네요. 

Service 계층 자체를 Session에서 자유롭게 만들어 줄 필요가 있다고 생각해서 이렇게 처리했었는데 그렇다면 Session 자체를 Service 계층에서 주입받아서 사용하는 것도 하나의 해결책이 될 수 있을까요?

2021-02-01 07:43 UTC, f-lab-dev commented on src/main/java/me/soo/helloworld/service/LoginService.java
> +    public void logout(HttpSession httpSession);
네 `HttpSession`은 외부에서 주입받을 수 있습니다~

2021-02-01 07:46 UTC, f-lab-dev requested changes

2021-02-01 07:46 UTC, f-lab-dev commented on src/main/java/me/soo/helloworld/model/user/UserIdAndPassword.java
> +public class UserIdAndPassword {
이 클래스는 로그인 요청정보를 담는 클래스이므로 `LoginRequest`가 낫지 않을까요?

2021-02-01 07:46 UTC, f-lab-dev commented on src/main/java/me/soo/helloworld/repository/UserRepository.java
> +    public UserIdAndPassword getRegisteredUserById(String userId) {
`RegisteredUser`가 결국 `User`아닐까요? `Registered`는 빼주셔도 될 것 같습니다~

2021-02-01 11:22 UTC, msugo1 commented on src/main/java/me/soo/helloworld/model/user/UserIdAndPassword.java
> +public class UserIdAndPassword {
변경했습니다! `LoginRequest` 바꿨더니 수정할 부분들이 좀 더 명확해지더라구요 감사합니다.

2021-02-01 11:22 UTC, msugo1 commented on src/main/java/me/soo/helloworld/repository/UserRepository.java
> +    public UserIdAndPassword getRegisteredUserById(String userId) {
`getUserById`로 변경했습니다.

2021-02-02 03:39 UTC, f-lab-dev approved these changes

2021-02-02 09:41 UTC, merged